apiVersion: apps/v1
kind: Deployment
metadata:
  name: xai-node-deployment
  namespace: xai-node
  labels:
    app: xai-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xai-node
  template:
    metadata:
      labels:
        app: xai-node
    spec:
      containers:
      - name: xai-node
        image: steddyman/xai-node:v1.2.0
        env:
        - name: PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: xai-node-key
              key: PRIVATE_KEY
        livenessProbe:
          exec:
            command:
            - /usr/local/bin/liveness.sh
          initialDelaySeconds: 30   # Delay before the first check
          periodSeconds: 120        # Check every 2 minutes
          timeoutSeconds: 10        # Time to wait for the probe to succeed
          failureThreshold: 2       # Number of consecutive failures to be considered failed
