name: Update on New Sentry Release

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight

  # Add a workflow_dispatch event to manually trigger the workflow
  workflow_dispatch:
    
jobs:
  update-on-new-release:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Check for new release in Sentry repository
      id: check-release
      run: |
        # Fetch the latest release tag from the Sentry repository
        LATEST_RELEASE_TAG=$(curl -s https://api.github.com/repos/xai-foundation/sentry/releases/latest | jq -r '.tag_name')
    
        # Read the last line in releases.txt
        LAST_PROCESSED_TAG=$(tail -n 1 releases.txt)
    
        # Check if the latest release tag is different from the last processed tag
        if [ "$LATEST_RELEASE_TAG" != "$LAST_PROCESSED_TAG" ]; then
          echo "New release found: $LATEST_RELEASE_TAG"
          echo "new_release_found=true" >> $GITHUB_OUTPUT
          echo "new_release_tag=$LATEST_RELEASE_TAG" >> $GITHUB_OUTPUT
        else
          echo "No new release found"
          echo "new_release_found=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Configure Git
      if: steps.check-release.outputs.new_release_found == 'true'
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'

    - name: Create a new branch
      if: steps.check-release.outputs.new_release_found == 'true'
      run: |
        git checkout -b update-to-${{ steps.check-release.outputs.new_release_tag }}

    - name: Update releases.txt
      if: steps.check-release.outputs.new_release_found == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "${{ steps.check-release.outputs.new_release_tag }}" >> releases.txt
        git add releases.txt
        git commit -m "Update to Sentry release ${{ steps.check-release.outputs.new_release_tag }}"

    - name: Push changes
      if: steps.check-release.outputs.new_release_found == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push origin update-to-${{ steps.check-release.outputs.new_release_tag }}


    - name: Create Pull Request
      if: steps.check-release.outputs.new_release_found == 'true'
      run: |
        gh pr create \
          --title "Version ${{ steps.check-release.outputs.new_release_tag }} Release" \
          --body "Update to Sentry release ${{ steps.check-release.outputs.new_release_tag }}" \
          --head update-to-${{ steps.check-release.outputs.new_release_tag }} \
          --base main

    - name: Enable Auto-Merge for Pull Request
      if: steps.check-release.outputs.new_release_found == 'true'
      run: |
        PR_NUMBER=$(gh pr view --json number --jq '.number')
        gh pr merge $PR_NUMBER --auto --squash

    - name: Wait for Pull Request to be merged
      if: steps.check-release.outputs.new_release_found == 'true'
      run: |
        PR_NUMBER=$(gh pr view --json number --jq '.number')
        while [ "$(gh pr view $PR_NUMBER --json merged --jq '.merged')" == "false" ]; do
          echo "Waiting for pull request #$PR_NUMBER to be merged..."
          sleep 5
        done
        echo "Pull request #$PR_NUMBER has been merged."

    - name: Create a new release
      if: steps.check-release.outputs.new_release_found == 'true'
      run: |
        gh release create v${{ steps.check-release.outputs.new_release_tag }} \
          --title "Release v${{ steps.check-release.outputs.new_release_tag }}" \
          --notes "New release matching Sentry release ${{ steps.check-release.outputs.new_release_tag }}"
  